try {
   console.log(existe) 
} catch(error) {
    console.log('nao existe')
}